### ISSUE TITLE
'RCTView.h' file not found, 'RCTViewManager.h' file not found, etc

### ISSUE THREAD

**Issue by faceyspacey** [greghe/react-native-particle-system#2]
And then the final errors I'm getting (when running `npm install`) is:

```
** BUILD FAILED **


The following build commands failed:
    CompileC Example/ios/build/Build/Intermediates/GPHParticleSystem.build/Debug-iphonesimulator/GPHParticleSystem.build/Objects-normal/x86_64/GPHParticleCellManager.o ParticleSystem-iOS/GPHParticleCellManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC Example/ios/build/Build/Intermediates/GPHParticleSystem.build/Debug-iphonesimulator/GPHParticleSystem.build/Objects-normal/x86_64/GPHParticleViewManager.o ParticleSystem-iOS/GPHParticleViewManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Installing build/Build/Products/Debug-iphonesimulator/ParticleDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/jamesgillmore/React/react-native-particle-system/Example/node_modules/promise/lib/done.js:10
      throw err;



Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ParticleDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at _runIOS (runIOS.js:77:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/jamesgillmore/React/react-native-particle-system/Example/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/jamesgillmore/React/react-native-particle-system/Example/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/jamesgillmore/React/react-native-particle-system/Example/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/jamesgillmore/React/react-native-particle-system/Example/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/Users/jamesgillmore/.nvm/versions/node/v5.6.0/lib/node_modules/react-native-cli/index.js:73:7)
```

All I did was git clone the repo, navigate to the Example and run `npm install`. Well, `sudo npm install` because the first time it seemed to have some file access issues. 

Maybe git clone this yourself to somewhere else your computer and see if it runs properly for you. There seem to be some paths to things only on your file system and not in the repo.

Also, in the readme, some directions for adding various files to Xcode and your build settings would be appreciated. I assume once npm install works, I'll have to do some of that. Really looking forward to using this to animate a background to the logo for a current project.

**Comment by greghe** [comment]
Probably an RN versioning issue. Let me make sure that the particle demo app is compatible with the latest RN.

**Comment by greghe** [comment]
To run the demo, get the latest source from github (I fixed a few typos in one of the .js files). Then from the command line, `cd` into the Examples folder and install its node dependencies by typing:

`npm install`

That will create a node_modules folder with a bunch of JS modules, including react-native. That is where the demo project is looking for the missing files.

**Comment by faceyspacey** [comment]
excellent. I'll check it out!

**Comment by faceyspacey** [comment]
still getting that issue where RCTView, RCTViewManager etc can't be imported:

http://snapplr.com/snap/6pnd

Within the demo's xcode project I tried adding the following header search paths to GPHParticleSystem.xcodeproj:

http://snapplr.com/snap/f385

**Comment by faceyspacey** [comment]
it's probably just a header search path issue. with everything I try, i can't seem to reach the React files. 

I'm no expert at xcode. But basically, if you prepare directions for how to add the package to an existing project where you have to add the files to your libraries, link the libraries, etc, my guess is it will work. This is as opposed to the demo where the xcodeproj is in the demo, etc. If it's setup the standard way where you first have to install the package to an existing app, and then add its corresponding files to xocde which now appear in your own node_modules, then things will likely iron themselves out.

**Comment by faceyspacey** [comment]
i figured out the header search paths issue. the issue is that the GPHParticleSystem.xcodeproj is in an usual place relative to your actual project. It's below Example. And the header search path before was:

$(SRCROOT)/node_modules/react-native/React

It needed to be:

$(SRCROOT)/Example/node_modules/react-native/React

**Comment by faceyspacey** [comment]
got it completely working!

...i had previously upgraded to React 23, so the final thing i had to do was add React as a peer dependency, and voila, it works! ...very nice my friend. I'm gonna play with it and get back to you.

**Comment by greghe** [comment]
Thanks for looking into getting the demo project properly configured. If you would like to open a pull request with your changes, I'd be happy to merge them in.

**Comment by MattFoley** [comment]
Changes I merged in today should fix the example project. Closing this out. If you still have trouble, let us know.
